### ISSUE TITLE
`cargo build` doesn't always pick up changes in components/ crates

### ISSUE THREAD

**Issue by fabricedesre** [fxbox/foxbox#424] opened 2016-04-25 16:31 UTC
STR:
- Do a full build with `cargo build`
- Introduce obvious syntax error in components/dnschallenge/mains.rs
- Run `cargo build` again.

Expected:
- We rebuild dnschallenge and foxbox.

Observed:
- We don't rebuild anything, so we have to run `cargo clean` first, and clobber the main foxbox crate.

I'm not sure if we can do everything we need in something driven by cargo or if we need to go the `mach` route like servo (that would make me a bit sad).

ping @JohanLorenzo @samgiles

**Comment by JohanLorenzo** [comment] 2016-04-25 17:47
I think this is caused by `build.rs` not being called because cargo didn't notice a file has changed. It doesn't occur with a library stored under `components/`.

I think we can solve it by either a Makefile/mach or making dns_challenge both a library and a binary. This library would be declared in the root `Cargo.toml` so it can detect any of its changes. What do you think @samgiles ?

**Comment by fabricedesre** [comment] 2016-04-25 17:54
Or we could maybe fix cargo to understand this kind of setup.

**Comment by julienw** [comment] 2016-04-28 17:52
should be fixed by ecc92fae61141185046ceaa7131a53a44258d4b4

**Closed as completed by julienw** 2016-04-28 17:52 UTC
Labels: Build
